name: EC2 deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EC2_CONNECTION_STRING: ubuntu@ec2-34-250-251-235.eu-west-1.compute.amazonaws.com

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        echo "hello world"
        echo "${{ secrets.EC2_PRIVATE_SECRET }}" > ec2-private-key.pem
        chmod 400 ec2-private-key.pem
        ssh -o StrictHostKeyChecking=no -i ec2-private-key.pem ${{ env.EC2_CONNECTION_STRING }} '
          date > current_time.txt

          # (만일 해당 디렉토리가 있으면)
          if [ -d $HOME/django-tutorial ]; then
            # git pull을 실행한다
            cd django-tutorial
            git pull origin main
          else # (없으면)
            # git repository로부터 파일을 클론한다
            git clone https://github.com/gotoweb/django-tutorial/
            cd django-tutorial
          fi
        '
